/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package pbb.express.views;

import pbb.express.Driver;
import pbb.express.model.account.Kurir;
import pbb.express.model.pesanan.Pesanan;

import javax.swing.*;

public class KurirFrame extends javax.swing.JFrame {
    
    private DefaultListModel<Pesanan> model;

    /** Creates new form KurirFrame */
    public KurirFrame() {
        initComponents();
        model = (DefaultListModel<Pesanan>) listKurirDaftarPesanan.getModel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listKurirDaftarPesanan = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        btnKurirCekAlamat = new javax.swing.JButton();
        labelKurirNomorResi = new javax.swing.JLabel();
        btnKurirCekMetodePembayaran = new javax.swing.JButton();
        btnKurirCekBarangSampai = new javax.swing.JButton();
        labelKurirNamaPengirim = new javax.swing.JLabel();
        labelKurirNamaPenerima = new javax.swing.JLabel();
        labelKurirNomorPengirim = new javax.swing.JLabel();
        labelKurirNomorPenerima = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        listKurirDaftarPesanan.setModel(new DefaultListModel<>());
        listKurirDaftarPesanan.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listKurirDaftarPesananValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listKurirDaftarPesanan);

        jLabel1.setText("Daftar Pesanan");

        btnKurirCekAlamat.setText("Cek Alamat");
        btnKurirCekAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurirCekAlamatActionPerformed(evt);
            }
        });

        labelKurirNomorResi.setText("Nomor Resi: ");

        btnKurirCekMetodePembayaran.setText("Cek Metode Pembayaran");
        btnKurirCekMetodePembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurirCekMetodePembayaranActionPerformed(evt);
            }
        });

        btnKurirCekBarangSampai.setText("Cek Barang Sampai");
        btnKurirCekBarangSampai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurirCekBarangSampaiActionPerformed(evt);
            }
        });

        labelKurirNamaPengirim.setText("Nama Pengirim: ");

        labelKurirNamaPenerima.setText("Nama Penerima:");

        labelKurirNomorPengirim.setText("Nomor Pengirim:");

        labelKurirNomorPenerima.setText("Nomor Penerima:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelKurirNomorResi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelKurirNomorPenerima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelKurirNamaPengirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelKurirNamaPenerima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelKurirNomorPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnKurirCekAlamat)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnKurirCekMetodePembayaran)
                                                .addGap(12, 12, 12)
                                                .addComponent(btnKurirCekBarangSampai)))
                                        .addGap(0, 6, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelKurirNomorResi)
                        .addGap(24, 24, 24)
                        .addComponent(labelKurirNamaPengirim)
                        .addGap(18, 18, 18)
                        .addComponent(labelKurirNomorPengirim)
                        .addGap(18, 18, 18)
                        .addComponent(labelKurirNamaPenerima)
                        .addGap(18, 18, 18)
                        .addComponent(labelKurirNomorPenerima)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKurirCekAlamat)
                            .addComponent(btnKurirCekMetodePembayaran)
                            .addComponent(btnKurirCekBarangSampai)))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listKurirDaftarPesananValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listKurirDaftarPesananValueChanged
        // TODO add your handling code here:
        Pesanan pesanan = listKurirDaftarPesanan.getSelectedValue();
        
        if (pesanan != null) {
            labelKurirNamaPenerima.setText("Nama Penerima: " + pesanan.getPenerima().getNamaPenerima());
            labelKurirNamaPengirim.setText("Nama Pengirim: " + pesanan.getPengirim().getNamaPengirim());
            
            labelKurirNomorPenerima.setText("Nomor Penerima: " + pesanan.getPenerima().getNomor());
            labelKurirNomorPengirim.setText("Nomor Pengirim: " + pesanan.getPengirim().getNomor());
            
            labelKurirNomorResi.setText("Nomor Resi: " + pesanan.getNomorResi());
        }
    }//GEN-LAST:event_listKurirDaftarPesananValueChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ViewHelper.tampilkanDaftarPesanan(model);
    }//GEN-LAST:event_formWindowOpened

    private void btnKurirCekAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurirCekAlamatActionPerformed
        // TODO add your handling code here:
        Pesanan pesanan = listKurirDaftarPesanan.getSelectedValue();
        
        if (pesanan != null) {
            JOptionPane.showMessageDialog(this, "Alamat Tujuan: " + ((Kurir) Driver.getLoggedAccount()).cekAlamat(pesanan));
        }
    }//GEN-LAST:event_btnKurirCekAlamatActionPerformed

    private void btnKurirCekMetodePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurirCekMetodePembayaranActionPerformed
        // TODO add your handling code here:
        Pesanan pesanan = listKurirDaftarPesanan.getSelectedValue();
        
        if (pesanan != null) {
            JOptionPane.showMessageDialog(this, ((Kurir) Driver.getLoggedAccount()).cekMetodePembayaran(pesanan));
        }
    }//GEN-LAST:event_btnKurirCekMetodePembayaranActionPerformed

    private void btnKurirCekBarangSampaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurirCekBarangSampaiActionPerformed
        // TODO add your handling code here:
        Pesanan pesanan = listKurirDaftarPesanan.getSelectedValue();
        
        if (pesanan != null) {
            ((Kurir) Driver.getLoggedAccount()).cekBarangSampai(pesanan);
            JOptionPane.showMessageDialog(this, "Barang sudah diterima Penerima");
        }
    }//GEN-LAST:event_btnKurirCekBarangSampaiActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ViewHelper.openFrame(new LoginFrame());
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKurirCekAlamat;
    private javax.swing.JButton btnKurirCekBarangSampai;
    private javax.swing.JButton btnKurirCekMetodePembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelKurirNamaPenerima;
    private javax.swing.JLabel labelKurirNamaPengirim;
    private javax.swing.JLabel labelKurirNomorPenerima;
    private javax.swing.JLabel labelKurirNomorPengirim;
    private javax.swing.JLabel labelKurirNomorResi;
    private javax.swing.JList<Pesanan> listKurirDaftarPesanan;
    // End of variables declaration//GEN-END:variables

}
