
package pbb.express.views;

import pbb.express.Driver;
import pbb.express.model.account.Admin;
import pbb.express.model.account.Penerima;
import pbb.express.model.account.Pengirim;
import pbb.express.model.pesanan.Barang;
import pbb.express.model.pesanan.Pesanan;
import pbb.express.sql.Database;

import javax.swing.*;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

public class AdminFrame extends javax.swing.JFrame {

    private final DefaultListModel<Pesanan> model;

    public AdminFrame() {
        initComponents();
        model = (DefaultListModel<Pesanan>) listAdminInfoPesanan.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogAdminInfoUbahLokasiBarang = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        textFieldAdminInfoDialogLokasi = new javax.swing.JTextField();
        btnAdminInfoDialogUbah = new javax.swing.JButton();
        btnAdminInfoDialogBatal = new javax.swing.JButton();
        dialogAdminInfoUbahPengirim = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        textFieldAdminInfoDialogUbahPengirimNama = new javax.swing.JTextField();
        btnAdminInfoDialogUbahPengirimUbah = new javax.swing.JButton();
        btnAdminInfoDialogUbahPengirimBatal = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAdminInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAdminInfoPesanan = new javax.swing.JList<>();
        labelAdminInfoPengirim = new javax.swing.JLabel();
        labelAdminInfoPenerima = new javax.swing.JLabel();
        labelAdminInfoLokasiBarang = new javax.swing.JLabel();
        labelAdminInfoResi = new javax.swing.JLabel();
        comboAdminStatusUpdate = new javax.swing.JComboBox<>();
        labelAdminInfoStatus = new javax.swing.JLabel();
        labelAdminInfoBiayaKirim = new javax.swing.JLabel();
        btnAdminInfoUbahLokasiBarang = new javax.swing.JButton();
        btnAdminInfoUbahPengirim = new javax.swing.JButton();
        btnAdminInfoHapus = new javax.swing.JButton();
        panelAdminTambah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldAdminTambahJenisBarang = new javax.swing.JTextField();
        textFieldAdminTambahNamaPenerima = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textFieldAdminTambahBeratBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textFieldAdminTambahLokasiBarang = new javax.swing.JTextField();
        textFieldAdminTambahNamaPengirim = new javax.swing.JTextField();
        btnAdminTambahTambahPesanan = new javax.swing.JButton();
        comboAdminTambahStatus = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnAdminTambahReset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        textFieldAdminTambahTarifPengiriman = new javax.swing.JTextField();

        dialogAdminInfoUbahLokasiBarang.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setText("Lokasi Barang");

        btnAdminInfoDialogUbah.setText("Ubah");
        btnAdminInfoDialogUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminInfoDialogUbahActionPerformed(evt);
            }
        });

        btnAdminInfoDialogBatal.setText("Batal");
        btnAdminInfoDialogBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminInfoDialogBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogAdminInfoUbahLokasiBarangLayout = new javax.swing.GroupLayout(dialogAdminInfoUbahLokasiBarang.getContentPane());
        dialogAdminInfoUbahLokasiBarang.getContentPane().setLayout(dialogAdminInfoUbahLokasiBarangLayout);
        dialogAdminInfoUbahLokasiBarangLayout.setHorizontalGroup(
            dialogAdminInfoUbahLokasiBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAdminInfoUbahLokasiBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogAdminInfoUbahLokasiBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(dialogAdminInfoUbahLokasiBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(dialogAdminInfoUbahLokasiBarangLayout.createSequentialGroup()
                            .addComponent(btnAdminInfoDialogUbah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdminInfoDialogBatal))
                        .addComponent(textFieldAdminInfoDialogLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        dialogAdminInfoUbahLokasiBarangLayout.setVerticalGroup(
            dialogAdminInfoUbahLokasiBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAdminInfoUbahLokasiBarangLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldAdminInfoDialogLokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(dialogAdminInfoUbahLokasiBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminInfoDialogUbah)
                    .addComponent(btnAdminInfoDialogBatal))
                .addContainerGap())
        );

        jLabel10.setText("Nama Pengirim:");

        btnAdminInfoDialogUbahPengirimUbah.setText("Ubah Nama");
        btnAdminInfoDialogUbahPengirimUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminInfoDialogUbahPengirimUbahActionPerformed(evt);
            }
        });

        btnAdminInfoDialogUbahPengirimBatal.setText("Batal");
        btnAdminInfoDialogUbahPengirimBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminInfoDialogUbahPengirimBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogAdminInfoUbahPengirimLayout = new javax.swing.GroupLayout(dialogAdminInfoUbahPengirim.getContentPane());
        dialogAdminInfoUbahPengirim.getContentPane().setLayout(dialogAdminInfoUbahPengirimLayout);
        dialogAdminInfoUbahPengirimLayout.setHorizontalGroup(
            dialogAdminInfoUbahPengirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAdminInfoUbahPengirimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogAdminInfoUbahPengirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldAdminInfoDialogUbahPengirimNama)
                    .addGroup(dialogAdminInfoUbahPengirimLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dialogAdminInfoUbahPengirimLayout.createSequentialGroup()
                        .addComponent(btnAdminInfoDialogUbahPengirimUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btnAdminInfoDialogUbahPengirimBatal)))
                .addContainerGap())
        );
        dialogAdminInfoUbahPengirimLayout.setVerticalGroup(
            dialogAdminInfoUbahPengirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAdminInfoUbahPengirimLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldAdminInfoDialogUbahPengirimNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogAdminInfoUbahPengirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminInfoDialogUbahPengirimUbah)
                    .addComponent(btnAdminInfoDialogUbahPengirimBatal))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setText("Daftar Pesanan");

        listAdminInfoPesanan.setModel(new DefaultListModel<>());
        listAdminInfoPesanan.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listAdminInfoPesananValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listAdminInfoPesanan);

        labelAdminInfoPengirim.setText("Pengirim: ");

        labelAdminInfoPenerima.setText("Penerima: ");

        labelAdminInfoLokasiBarang.setText("Lokasi Barang: ");

        labelAdminInfoResi.setText("Resi: ");

        comboAdminStatusUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Dikirim", "Diperjalanan", "Diterima" }));
        comboAdminStatusUpdate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAdminStatusUpdateItemStateChanged(evt);
            }
        });

        labelAdminInfoStatus.setText("Status");

        labelAdminInfoBiayaKirim.setText("Biaya Kirim: ");

        btnAdminInfoUbahLokasiBarang.setText("Ubah Lokasi Barang");
        btnAdminInfoUbahLokasiBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminInfoUbahLokasiBarangActionPerformed(evt);
            }
        });

        btnAdminInfoUbahPengirim.setText("Ubah Data Pengirim");
        btnAdminInfoUbahPengirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminInfoUbahPengirimActionPerformed(evt);
            }
        });

        btnAdminInfoHapus.setText("Hapus");
        btnAdminInfoHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminInfoHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAdminInfoLayout = new javax.swing.GroupLayout(panelAdminInfo);
        panelAdminInfo.setLayout(panelAdminInfoLayout);
        panelAdminInfoLayout.setHorizontalGroup(
            panelAdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAdminInfoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelAdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAdminInfoPenerima, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAdminInfoPengirim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAdminInfoLokasiBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAdminInfoResi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelAdminInfoBiayaKirim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelAdminInfoLayout.createSequentialGroup()
                                .addComponent(btnAdminInfoUbahLokasiBarang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAdminInfoHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(btnAdminInfoUbahPengirim))
                            .addGroup(panelAdminInfoLayout.createSequentialGroup()
                                .addComponent(labelAdminInfoStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboAdminStatusUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelAdminInfoLayout.setVerticalGroup(
            panelAdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminInfoLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminInfoLayout.createSequentialGroup()
                        .addComponent(labelAdminInfoPengirim)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(labelAdminInfoPenerima)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(labelAdminInfoLokasiBarang)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(labelAdminInfoResi)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(labelAdminInfoBiayaKirim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(panelAdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAdminInfoStatus)
                            .addComponent(comboAdminStatusUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(panelAdminInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdminInfoUbahLokasiBarang)
                            .addComponent(btnAdminInfoUbahPengirim)
                            .addComponent(btnAdminInfoHapus)))
                    .addComponent(jScrollPane1))
                .addGap(12, 12, 12))
        );

        jTabbedPane1.addTab("Daftar Pesanan", panelAdminInfo);

        jLabel1.setText("Jenis Barang");

        jLabel3.setText("Nama Penerima");

        jLabel4.setText("Berat Barang (kg)");

        jLabel6.setText("Lokasi Barang");

        jLabel7.setText("Nama Pengirim");

        btnAdminTambahTambahPesanan.setText("Tambah Pesanan");
        btnAdminTambahTambahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminTambahTambahPesananActionPerformed(evt);
            }
        });

        comboAdminTambahStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Dikirim", "Diperjalanan", "Diterima" }));

        jLabel5.setText("Status");

        btnAdminTambahReset.setText("Reset");
        btnAdminTambahReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminTambahResetActionPerformed(evt);
            }
        });

        jLabel9.setText("Tarif Pengiriman");

        javax.swing.GroupLayout panelAdminTambahLayout = new javax.swing.GroupLayout(panelAdminTambah);
        panelAdminTambah.setLayout(panelAdminTambahLayout);
        panelAdminTambahLayout.setHorizontalGroup(
            panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAdminTambahLayout.createSequentialGroup()
                        .addComponent(btnAdminTambahTambahPesanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdminTambahReset))
                    .addComponent(jLabel9)
                    .addGroup(panelAdminTambahLayout.createSequentialGroup()
                        .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textFieldAdminTambahTarifPengiriman, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textFieldAdminTambahLokasiBarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(textFieldAdminTambahJenisBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldAdminTambahBeratBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel6)))
                        .addGap(48, 48, 48)
                        .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAdminTambahStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(textFieldAdminTambahNamaPenerima)
                                .addComponent(jLabel7)
                                .addComponent(textFieldAdminTambahNamaPengirim, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        panelAdminTambahLayout.setVerticalGroup(
            panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminTambahLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAdminTambahJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAdminTambahNamaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAdminTambahBeratBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAdminTambahNamaPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAdminTambahLokasiBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAdminTambahStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldAdminTambahTarifPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(panelAdminTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminTambahTambahPesanan)
                    .addComponent(btnAdminTambahReset))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tambah Pesanan", panelAdminTambah);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ViewHelper.openFrame(new LoginFrame());
    }//GEN-LAST:event_formWindowClosing

    private void btnAdminTambahResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminTambahResetActionPerformed
        // TODO add your handling code here:
        textFieldAdminTambahBeratBarang.setText("");
        textFieldAdminTambahJenisBarang.setText("");
        textFieldAdminTambahLokasiBarang.setText("");
        textFieldAdminTambahNamaPenerima.setText("");
        textFieldAdminTambahNamaPengirim.setText("");
    }//GEN-LAST:event_btnAdminTambahResetActionPerformed

    private void btnAdminTambahTambahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminTambahTambahPesananActionPerformed
        // TODO add your handling code here:
        
        // Dapetin semua data pesanan
        String jenisBarang = textFieldAdminTambahJenisBarang.getText();
        String namaPenerima = textFieldAdminTambahNamaPenerima.getText();
        String namaPengirim = textFieldAdminTambahNamaPengirim.getText();
        String lokasiBarang = textFieldAdminTambahLokasiBarang.getText();
        String beratBarang = textFieldAdminTambahBeratBarang.getText();
        String status = comboAdminTambahStatus.getSelectedItem().toString();
        String tarifPengiriman = textFieldAdminTambahTarifPengiriman.getText();

        
        // Cek semua data ada yang kosong ato tidak
        if(jenisBarang.isEmpty() || namaPenerima.isEmpty() || namaPengirim.isEmpty() || lokasiBarang.isEmpty() || beratBarang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong");
        }else {
            // Bikin objek barang
            try{
                Barang barang = new Barang(jenisBarang, Integer.parseInt(beratBarang), lokasiBarang);

                // Get penerima & pengirim from database
                Penerima penerima = new Penerima(namaPenerima);
                Pengirim pengirim = new Pengirim(namaPengirim);

                // Bikin objek pesanan
                Pesanan pesanan = new Pesanan(pengirim, penerima, barang, Integer.parseInt(tarifPengiriman), status);
                
                // Tambahin pesanan ke database
                ((Admin) Driver.getLoggedAccount()).addData(pesanan);

                // Tampilin pesan
                JOptionPane.showMessageDialog(this, "Pesanan berhasil ditambahkan");
                textFieldAdminTambahBeratBarang.setText("");
                textFieldAdminTambahLokasiBarang.setText("");
                textFieldAdminTambahJenisBarang.setText("");
                textFieldAdminTambahNamaPenerima.setText("");
                textFieldAdminTambahNamaPengirim.setText("");
                textFieldAdminTambahTarifPengiriman.setText("");
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Input berat dan tarif harus angka");
            }
        }
        
    }//GEN-LAST:event_btnAdminTambahTambahPesananActionPerformed

    private void listAdminInfoPesananValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listAdminInfoPesananValueChanged
        // TODO add your handling code here:
        Pesanan pesanan = listAdminInfoPesanan.getSelectedValue();

        if(pesanan != null) {
            labelAdminInfoLokasiBarang.setText("Lokasi Barang : " + pesanan.getBarang().getLokasiBarang());
            labelAdminInfoPenerima.setText("Nama Penerima : " + pesanan.getPenerima().getNamaPenerima());
            labelAdminInfoPengirim.setText("Nama Pengirim : " + pesanan.getPengirim().getNamaPengirim());
            labelAdminInfoResi.setText("Resi : " + pesanan.getNomorResi());
            labelAdminInfoBiayaKirim.setText("Tarif Pengiriman : " + pesanan.getBiayaKirim());

            ComboBoxModel<String> comboModel = comboAdminStatusUpdate.getModel();
            for (int i = 0; i < comboModel.getSize(); i++) {
                if(comboModel.getElementAt(i).equalsIgnoreCase(pesanan.getStatus())) {
                    comboAdminStatusUpdate.setSelectedIndex(i);
                }
            }
        }
    }//GEN-LAST:event_listAdminInfoPesananValueChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ViewHelper.tampilkanDaftarPesanan(model);
    }//GEN-LAST:event_formWindowOpened

    private void comboAdminStatusUpdateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAdminStatusUpdateItemStateChanged
        // TODO add your handling code here:
        String selectedStatus = comboAdminStatusUpdate.getSelectedItem().toString();
        Pesanan pesanan = listAdminInfoPesanan.getSelectedValue();

        try {
            PreparedStatement ps = Database.getInstance().getConnection().prepareStatement("UPDATE pesanan SET status = ? WHERE nomor_resi = ?");
            ps.setString(1, selectedStatus);
            ps.setString(2, pesanan.getNomorResi());

            ps.executeUpdate();

            ps.close();

            pesanan.setStatus(selectedStatus);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_comboAdminStatusUpdateItemStateChanged

    private void btnAdminInfoUbahLokasiBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminInfoUbahLokasiBarangActionPerformed
        // TODO add your handling code here:
        // Ambil pesanan dari list yang dipilih
        Pesanan pesanan = listAdminInfoPesanan.getSelectedValue();
        
        // Cek kalo pesanan itu beneran atau ndak
        if (pesanan == null) {
            JOptionPane.showMessageDialog(this, "Harap pilih pesanan");
            return;
        }
        
        // Tampilin view buat ke halaman update lokasi
        dialogAdminInfoUbahLokasiBarang.pack();
        dialogAdminInfoUbahLokasiBarang.setVisible(true);
        
        // Set data di view agar sesuai dengan objek pesanan saat ini
        textFieldAdminInfoDialogLokasi.setText(pesanan.getBarang().getLokasiBarang());
    }//GEN-LAST:event_btnAdminInfoUbahLokasiBarangActionPerformed

    private void btnAdminInfoDialogUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminInfoDialogUbahActionPerformed
        // TODO add your handling code here:
        
        // Dapetin koneksi database
        Connection connection = Database.getInstance().getConnection();
        
        // Dapetin pesanan yang dipilih sekarang
        Pesanan pesanan = listAdminInfoPesanan.getSelectedValue();
        
        try {
            // Bikin statement yang akan dipakai ke database
            PreparedStatement ps = connection.prepareStatement("UPDATE barang SET lokasi_barang = ? WHERE jenis_barang = ? AND berat_barang = ? AND lokasi_barang = ?");
            
            // Set data yang ingin dipakai buat query database
            ps.setString(1, textFieldAdminInfoDialogLokasi.getText());
            ps.setString(2, pesanan.getBarang().getJenisBarang());
            ps.setInt(3, pesanan.getBarang().getBeratBarang());
            ps.setString(4, pesanan.getBarang().getLokasiBarang());
            
            // Eksekusi query diatas
            ps.executeUpdate();
            
            // Kita tutup koneksi dan tampilkan pesan 
            ps.close();
            JOptionPane.showMessageDialog(dialogAdminInfoUbahLokasiBarang, "Lokasi telah diubah");
            dialogAdminInfoUbahLokasiBarang.dispose();
            
            // Update data di list
            ViewHelper.tampilkanDaftarPesanan(model);
        } catch (SQLException ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAdminInfoDialogUbahActionPerformed

    private void btnAdminInfoDialogBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminInfoDialogBatalActionPerformed
        // TODO add your handling code here:
        dialogAdminInfoUbahLokasiBarang.dispose();
    }//GEN-LAST:event_btnAdminInfoDialogBatalActionPerformed

    private void btnAdminInfoDialogUbahPengirimBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminInfoDialogUbahPengirimBatalActionPerformed
        // TODO add your handling code here:
        dialogAdminInfoUbahPengirim.dispose();
    }//GEN-LAST:event_btnAdminInfoDialogUbahPengirimBatalActionPerformed

    private void btnAdminInfoDialogUbahPengirimUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminInfoDialogUbahPengirimUbahActionPerformed
        // TODO add your handling code here:
        Connection connection = Database.getInstance().getConnection();
        
        String newName = textFieldAdminInfoDialogUbahPengirimNama.getText();
        Pesanan pesanan = listAdminInfoPesanan.getSelectedValue();
        
        try {
            PreparedStatement akunPs = connection.prepareStatement("SELECT id FROM akun WHERE nama = ? AND jenis_akun_id = ?");
            
            akunPs.setString(1, newName);
            akunPs.setInt(2, 4);
            
            ResultSet akunRs = akunPs.executeQuery();
            
            if (akunRs.next()) {
                int pengirimId = akunRs.getInt("id");
                
                PreparedStatement ps = connection.prepareStatement("UPDATE pesanan SET pengirim_id = ? WHERE nomor_resi = ?");
                
                ps.setInt(1, pengirimId);
                ps.setString(2, pesanan.getNomorResi());
                
                ps.executeUpdate();
                
                JOptionPane.showMessageDialog(dialogAdminInfoUbahPengirim, "Nama pengirim telah diubah");
                
                dialogAdminInfoUbahPengirim.dispose();
                ViewHelper.tampilkanDaftarPesanan(model);
                
                ps.close();
            }else {
                JOptionPane.showMessageDialog(dialogAdminInfoUbahPengirim, "Nama pengirim tidak ditemukan");
            }
            
            akunPs.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdminInfoDialogUbahPengirimUbahActionPerformed

    private void btnAdminInfoUbahPengirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminInfoUbahPengirimActionPerformed
        // TODO add your handling code here:
        Pesanan pesanan = listAdminInfoPesanan.getSelectedValue();
        if (pesanan == null) {
            JOptionPane.showConfirmDialog(this, "Harap pilih pesanan");
            return;
        }
        
        dialogAdminInfoUbahPengirim.pack();
        dialogAdminInfoUbahPengirim.setVisible(true);
        
        textFieldAdminInfoDialogUbahPengirimNama.setText(pesanan.getPengirim().getNamaPengirim());
    }//GEN-LAST:event_btnAdminInfoUbahPengirimActionPerformed

    private void btnAdminInfoHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminInfoHapusActionPerformed
        // TODO add your handling code here:
        Pesanan pesanan = listAdminInfoPesanan.getSelectedValue();
        
        if (pesanan != null) {
            try {
                PreparedStatement ps = Database.getInstance().getConnection().prepareStatement("DELETE FROM pesanan WHERE nomor_resi = ?");
                
                ps.setString(1, pesanan.getNomorResi());
                
                ps.executeUpdate();
                
                ps.close();
                
                JOptionPane.showMessageDialog(this, "Pesanan telah dihapus");
                
                ViewHelper.tampilkanDaftarPesanan(model);
            } catch (SQLException ex) {
                Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnAdminInfoHapusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminInfoDialogBatal;
    private javax.swing.JButton btnAdminInfoDialogUbah;
    private javax.swing.JButton btnAdminInfoDialogUbahPengirimBatal;
    private javax.swing.JButton btnAdminInfoDialogUbahPengirimUbah;
    private javax.swing.JButton btnAdminInfoHapus;
    private javax.swing.JButton btnAdminInfoUbahLokasiBarang;
    private javax.swing.JButton btnAdminInfoUbahPengirim;
    private javax.swing.JButton btnAdminTambahReset;
    private javax.swing.JButton btnAdminTambahTambahPesanan;
    private javax.swing.JComboBox<String> comboAdminStatusUpdate;
    private javax.swing.JComboBox<String> comboAdminTambahStatus;
    private javax.swing.JDialog dialogAdminInfoUbahLokasiBarang;
    private javax.swing.JDialog dialogAdminInfoUbahPengirim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAdminInfoBiayaKirim;
    private javax.swing.JLabel labelAdminInfoLokasiBarang;
    private javax.swing.JLabel labelAdminInfoPenerima;
    private javax.swing.JLabel labelAdminInfoPengirim;
    private javax.swing.JLabel labelAdminInfoResi;
    private javax.swing.JLabel labelAdminInfoStatus;
    private javax.swing.JList<Pesanan> listAdminInfoPesanan;
    private javax.swing.JPanel panelAdminInfo;
    private javax.swing.JPanel panelAdminTambah;
    private javax.swing.JTextField textFieldAdminInfoDialogLokasi;
    private javax.swing.JTextField textFieldAdminInfoDialogUbahPengirimNama;
    private javax.swing.JTextField textFieldAdminTambahBeratBarang;
    private javax.swing.JTextField textFieldAdminTambahJenisBarang;
    private javax.swing.JTextField textFieldAdminTambahLokasiBarang;
    private javax.swing.JTextField textFieldAdminTambahNamaPenerima;
    private javax.swing.JTextField textFieldAdminTambahNamaPengirim;
    private javax.swing.JTextField textFieldAdminTambahTarifPengiriman;
    // End of variables declaration//GEN-END:variables
}
