/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package pbb.express.views;

import pbb.express.Driver;
import pbb.express.model.account.Penerima;
import pbb.express.model.pesanan.Pesanan;

import javax.swing.*;

public class PenerimaFrame extends javax.swing.JFrame {
    
    private DefaultListModel<Pesanan> model;

    /** Creates new form PenerimaFrame */
    public PenerimaFrame() {
        initComponents();
        model = (DefaultListModel<Pesanan>) listPenerimaDaftarKiriman.getModel();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPenerimaGreeting = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPenerimaDaftarKiriman = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        labelPenerimaNamaPengirim = new javax.swing.JLabel();
        labelPenerimaNomorPengirim = new javax.swing.JLabel();
        labelPenerimaLokasiBarang = new javax.swing.JLabel();
        labelPenerimaStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelPenerimaGreeting.setText("Halo, " + ((Penerima) Driver.getLoggedAccount()).getNamaPenerima());

        listPenerimaDaftarKiriman.setModel(new DefaultListModel<>());
        listPenerimaDaftarKiriman.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listPenerimaDaftarKirimanValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listPenerimaDaftarKiriman);

        jLabel2.setText("Daftar Kiriman");

        labelPenerimaNamaPengirim.setText("Nama Pengirim: ");

        labelPenerimaNomorPengirim.setText("Nomor Pengirim:");

        labelPenerimaLokasiBarang.setText("Lokasi Barang: ");

        labelPenerimaStatus.setText("Status:: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPenerimaNamaPengirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPenerimaNomorPengirim, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(labelPenerimaLokasiBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPenerimaStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(labelPenerimaGreeting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPenerimaGreeting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPenerimaNamaPengirim)
                        .addGap(30, 30, 30)
                        .addComponent(labelPenerimaNomorPengirim)
                        .addGap(33, 33, 33)
                        .addComponent(labelPenerimaLokasiBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(labelPenerimaStatus)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // TODO add your handling code here:
        ViewHelper.tampilkanDaftarPesanan(model);
    }//GEN-LAST:event_formWindowOpened

    private void listPenerimaDaftarKirimanValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listPenerimaDaftarKirimanValueChanged
        // TODO add your handling code here:
        
        Pesanan pesanan = listPenerimaDaftarKiriman.getSelectedValue();
        
        if (pesanan != null) {
            labelPenerimaLokasiBarang.setText("Lokasi Barang: " + pesanan.getBarang().getLokasiBarang());
            labelPenerimaNamaPengirim.setText("Nama Pengirim: " + pesanan.getPengirim().getNamaPengirim());
            labelPenerimaNomorPengirim.setText("Nomor Pengirim: " + pesanan.getPengirim().getNomor());
            labelPenerimaStatus.setText("Status: " + pesanan.getStatus());
            
        }
        
    }//GEN-LAST:event_listPenerimaDaftarKirimanValueChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ViewHelper.openFrame(new LoginFrame());
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPenerimaGreeting;
    private javax.swing.JLabel labelPenerimaLokasiBarang;
    private javax.swing.JLabel labelPenerimaNamaPengirim;
    private javax.swing.JLabel labelPenerimaNomorPengirim;
    private javax.swing.JLabel labelPenerimaStatus;
    private javax.swing.JList<Pesanan> listPenerimaDaftarKiriman;
    // End of variables declaration//GEN-END:variables

}
